version: '3.1'
services:
  mongo:
    image: mongo
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rafaelcruz
      MONGO_INITDB_ROOT_PASSWORD: 123456#A
    ports:
        - 27017:27017
    volumes: 
        - /var/data/mongo:/data/db
    networks: 
        - mongo_network
  mongo-express:
    image: mongo-express
    restart: "no"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rafaelcruz
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456#A
    networks: 
       - mongo_network
networks: 
    mongo_network:
        driver: bridge